"""empty message

Revision ID: 07ca06db1401
Revises: 4388209ed92a
Create Date: 2022-11-07 19:00:21.975259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ca06db1401'
down_revision = '4388209ed92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('important', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'important')
    # ### end Alembic commands ###
