"""empty message

Revision ID: b94e309f7839
Revises: 22d420db1437
Create Date: 2022-10-19 20:32:25.562961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b94e309f7839'
down_revision = '22d420db1437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'situation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('situation', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
