"""empty message

Revision ID: d7858479e236
Revises: 07ca06db1401
Create Date: 2022-11-08 23:43:20.074508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7858479e236'
down_revision = '07ca06db1401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='email_captcha')
    op.drop_table('email_captcha')
    op.drop_index('email', table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('email_captcha',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('captcha', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'email_captcha', ['email'], unique=False)
    # ### end Alembic commands ###
