"""empty message

Revision ID: e6b3d0654a7c
Revises: b94e309f7839
Create Date: 2022-10-21 23:44:06.778973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b3d0654a7c'
down_revision = 'b94e309f7839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
